Repository BioDynaMo/biodynamo, pull requests merged in 2022-10, with the labels that each got.

#260 Generalize continuum integration
  cmake/selection-libbiodynamo.xml
  cmake/selection.xml
  demo/analytic_continuum/CMakeLists.txt
  demo/analytic_continuum/README.md
  demo/analytic_continuum/bdm.json
  demo/analytic_continuum/src/analytic_continuum.cc
  demo/analytic_continuum/src/analytic_continuum.h
  demo/analytic_continuum/src/continuum_model.h
  demo/analytic_continuum/src/my_agent.h
  demo/analytic_continuum/src/my_behavior.h
  demo/analytic_continuum/thumbnail.png
  demo/binding_cells/src/biology_modules/inhibitation_module.h
  demo/gene_regulation/src/gene_regulation.h
  src/core/behavior/chemotaxis.h
  src/core/behavior/gene_regulation.h
  src/core/behavior/secretion.h
  src/core/diffusion/continuum_interface.cc
  src/core/diffusion/continuum_interface.h
  src/core/diffusion/diffusion_grid.cc
  src/core/diffusion/diffusion_grid.h
  src/core/model_initializer.cc
  src/core/operation/continuum_op.h
  src/core/operation/default_ops.cc
  src/core/resource_manager.cc
  src/core/resource_manager.h
  src/core/scheduler.cc
  src/core/simulation.cc
  src/core/visualization/paraview/adaptor.cc
  test/unit/core/behavior/gene_regulation_test.cc
  test/unit/core/behavior/secretion_test.cc
  test/unit/core/continuum_test.cc
  test/unit/core/diffusion_init_test.cc
  test/unit/core/diffusion_test.cc
  test/unit/core/resource_manager_test.cc
  test/unit/core/resource_manager_test.h
  test/unit/core/scheduler_test.cc
Labels: api-change, examples, bdm-core, ready

#279 Fix Python libraries on macOS
  CMakeLists.txt
Labels: bug, build-system, ready

#287 Fix macos openmp
  CMakeLists.txt
  cmake/UseBioDynaMo.cmake.in
  cmake/env/thisbdm.fish
  cmake/env/thisbdm.sh
Labels: build-system, ready
