Repository BioDynaMo/biodynamo, pull requests merged in 2023-02, with the labels that each got.

#284 Allow both manual and automatic randomization of agents ordering
  src/core/randomized_rm.h
  test/unit/core/randomized_rm_test.cc
Labels: enhancement, ready-for-review, bdm-core

#258 Resolution Fix, Boundaries, and Depletion
  cmake/selection-libbiodynamo.xml
  cmake/selection.xml
  demo/diffusion/src/diffusion.h
  doc/user_guide/diffusion.md
  src/core/diffusion/diffusion_grid.cc
  src/core/diffusion/diffusion_grid.h
  src/core/diffusion/euler_depletion_grid.cc
  src/core/diffusion/euler_depletion_grid.h
  src/core/diffusion/euler_grid.cc
  src/core/diffusion/euler_grid.h
  src/core/diffusion/runge_kutta_grid.cc
  src/core/diffusion/runge_kutta_grid.h
  src/core/model_initializer.cc
  src/core/model_initializer.h
  src/core/param/param.h
  test/unit/core/diffusion_init_test.cc
  test/unit/core/diffusion_init_test.h
  test/unit/core/diffusion_test.cc
  test/unit/core/model_initializer_test.cc
Labels: api-change, bdm-core, ready

#312 Add different time units to `ProgressBar`
  demo/analytic_continuum/bdm.json
  src/core/param/param.h
  src/core/scheduler.cc
  src/core/util/progress_bar.cc
  src/core/util/progress_bar.h
Labels: enhancement, ready

#314 Add `DataTransformer` for `TimeSeries::Data`
  cmake/selection-libbiodynamo.xml
  cmake/selection.xml
  src/core/analysis/time_series.cc
  src/core/analysis/time_series.h
  test/unit/core/analysis/time_series_test.cc
Labels: enhancement, ready-for-review

#313 Fixed soma clustering demo
  demo/soma_clustering/src/soma_clustering.h
Labels: examples, ready

#318 Add resolution independent version of `DG::ChangeConcentrationBy`
  src/core/diffusion/diffusion_grid.cc
  src/core/diffusion/diffusion_grid.h
  test/unit/core/diffusion_test.cc
Labels: enhancement, ready-for-review, coupling

#319 Remove Slack notifications from CI
  .github/workflows/centos-ci.yml
  .github/workflows/centos-system-ci.yml
  .github/workflows/gitpod.yml
  .github/workflows/macos-ci.yml
  .github/workflows/macos-system-ci.yml
  .github/workflows/repostory-checks.yml
  .github/workflows/sonar-source.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/ubuntu-system-ci.yml
  doc/dev_guide/contribute.md
Labels: ready-for-review

#316 Enable double precision in OpenCL kernel when compatible GPU is found
  src/core/gpu/gpu_helper.cc
  src/core/gpu/opencl_state.cc
  src/core/gpu/opencl_state.h
  src/core/param/param.h
Labels: enhancement, GPU

#321 Fix discretization offsets in DG
  src/core/diffusion/diffusion_grid.cc
  src/core/visualization/paraview/vtk_diffusion_grid.cc
  test/unit/core/diffusion_init_test.cc
  test/unit/core/visualization/paraview/integration_test.cc
Labels: enhancement, ready, ParaView, diffusion, coupling
