Repository BioDynaMo/biodynamo, pull requests merged in 2023-11, with the labels that each got.

#349 HPC documentation
  doc/user_guide/Singularity.md
Labels: documentation

#350 Deprecate `macOS` < 12.0
  .github/workflows/macos-ci.yml
  .github/workflows/macos-system-ci.yml
  doc/user_guide/installation.md
  doc/user_guide/prerequisites.md
Labels: ready-for-review, operating-system, CI

#348 Update to Java 17 in SonarCI
  .github/workflows/sonar-source.yml
Labels: maintenance, CI
